import Image from "next/image";
import Link from "next/link";
import React from "react";
import Head from "next/head";

export default function Layout({children}) {
  let days = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];

  return (
    <>
      <div className='container'>
        <Head>
          <title>Advent of Code 2022</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main>
          <nav>
            <Image className='logo' src='/snowman.svg' width={90} height={90}
                   alt='The Snowman of the Advent of Code'/>
            <ul>
              {days.map(day => (
                <li key={day}>
                  <Link href={`/day/day${day}`}>{days[day - 1]}</Link>
                </li>
              ))}
            </ul>
          </nav>

          <div className='day'>
            {children}
          </div>
        </main>

        <footer>
          <a href='https://adventofcode.com/'>Advent of Code 2022</a>
        </footer>
      </div>
    </>
  )
}